name: Compile

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout OpenCV
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
          path: opencv
      - name: Checkout OpenCV Contrib
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv_contrib
          path: opencv-contrib
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: emsdk-cache
          key: emsdk-cache
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          actions-cache-folder: emsdk-cache
      - name: Compile
        run: emcmake ./compile.sh
